image:
    file: .gitpod.Dockerfile
    context: .
tasks:
    - command: |
          make setup
vscode:
  extensions:
    - svelte.svelte-vscode
    - ziglang.vscode-zig
    - vadimcn.vscode-lldb
    - ms-vscode.makefile-tools
    - oven.bun-vscode
    - ms-azuretools.vscode-docker
    - ms-vscode-remote.remote-containers
    - gitpod.gitpod-desktop
    - github.vscode-github-actions
    - GitHub.codespaces
    - bierner.markdown-preview-github-styles
    - bierner.markdown-mermaid
    - dtoplak.vscode-glsllint
    - rust-lang.rust-analyzer
    - tamasfe.even-better-toml
    - redhat.vscode-yaml
    - amazonwebservices.aws-toolkit-vscode
    - ms-python.python