AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: SAM template for Rust binaries

Parameters:
  SslCertificateArn:
    Type: String
    Description: ARN of the ACM certificate for custom domain
  DomainName:
    Type: String
    Description: Domain name for the API Gateway custom domain
    Default: dylanlangston.com
  BucketName:
    Type: String
    Description: Name of the S3 bucket for static website hosting
    Default: test.dylanlangston.com

Resources:
  RustFunctionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: LambdaSESAccessPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action: ses:SendEmail
                Resource: '*'

  RustFunction:
    Type: AWS::Serverless::Function 
    Properties:
      CodeUri: contact-lambda/target/contact-lambda/bootstrap.zip
      Handler: rust.handler
      Runtime: provided.al2023
      Role: !GetAtt RustFunctionRole.Arn
      Architectures:
        - arm64
      Events:
        ContactPOST:
          Type: Api
          Properties:
            Path: /contact
            Method: POST
        ContactOptions:
          Type: Api
          Properties:
            Path: /contact
            Method: OPTIONS

Outputs:
  RustFunction:
    Description: "Lambda Function ARN"
    Value: !GetAtt RustFunction.Arn

  ApiUrl:
    Description: "API Gateway URL"
    Value: !Sub "https://api.${DomainName}/contact"
