name: 'Version String'
description: 'Outputs the version string based on an input date'
inputs:
  time:
    description: 'Time this version was build'
    required: true
outputs:
  version:
    description: "Version String"
    value: ${{ steps.set_datetime.outputs.version }}
runs:
  using: "composite"
  steps:
    - name: Set datetime output variable
      uses: actions/github-script@v7
      id: set_datetime
      with:
        result-encoding: string
        script: |
          const script = require('./VersionString.js')
          script({core});