name: 'Version String'
description: 'Outputs the version string based on an input date'
inputs:
  time:
    description: 'Time this version was build'
    required: true
    type: string
outputs:
  version:
    description: "Version String"
    value: ${{ steps.set_datetime.outputs.version }}
    type: string
runs:
  using: "node20"
  main: "main.mjs"
branding:
  icon: 'git-commit'
  color: 'green'