name: 'AWS SAM CLI Deploy'
description: 'Deploy the application to AWS using SAM CLI'
inputs:
  aws-region:
    description: 'AWS Region'
    required: true
  aws-access-key-id:
    description: 'AWS Access Key'
    required: true
  aws-secret-access-key:
    description: 'AWS Secret Key'
    required: true
  aws-acm-arn:
    description: 'AWS ACM ARN'
    required: true
runs:
  using: "composite"
  steps:
    - name: Add mask
      shell: sh
      run: |
        echo "::add-mask::${{ inputs.aws-access-key-id }}"
        echo "::add-mask::${{ inputs.aws-secret-access-key }}"
        echo "::add-mask::${{ inputs.aws-acm-arn }}"
    - name: Setup SAM     
      shell: sh
      run: |
        sudo apt-get -y install --no-install-recommends awscli
        curl -L "https://github.com/aws/aws-sam-cli/releases/latest/download/aws-sam-cli-linux-x86_64.zip" -o sam.zip
        unzip sam.zip -d ./sam
        rm sam.zip
        sudo ./sam/install --update
        rm -rf ./sam
    - name: Set up AWS credentials
      shell: sh
      run: |
        aws configure set aws_access_key_id ${{ inputs.aws-access-key-id }}
        aws configure set aws_secret_access_key ${{ inputs.aws-secret-access-key }}
        aws configure set default.region ${{ inputs.aws-region }}
        aws configure set default.output json
    - name: Stage Artifacts 
      shell: sh
      run: |
        ls -lah
        pwd
        unzip ./artifacts/dylanlangston.com-v*.zip -d ./site/build
        unzip ./artifacts/dylanlangston.com-contact-v*.zip -d ./contact-lambda/target/contact-lambda
    - name: Deploy with SAM
      shell: sh
      run: |
        sam deploy --parameter-overrides SslCertificateArn=${{ inputs.aws-acm-arn }}
branding:
  icon: 'server'
  color: 'green'