name: 'AWS SAM CLI Deploy'
description: 'Deploy the application to AWS using SAM CLI'
inputs:
  aws-access-key-id:
    description: 'AWS Access Key'
    required: true
  aws-secret-access-key:
    description: 'AWS Secret Key'
    required: true
  aws-region:
    description: 'AWS Region'
    required: true
runs:
  using: "composite"
  steps:          
    - name: Setup Python     
      uses: actions/setup-python@v5.0.0
    - name: Setup SAM     
      uses: aws-actions/setup-sam@v2
    - name: Set up AWS credentials
      shell: sh
      run: |
        aws configure set aws_access_key_id ${{ inputs.target }}
        aws configure set aws_secret_access_key ${{ inputs.target }}
        aws configure set default.region ${{ inputs.aws-region }}
        aws configure set default.output json
branding:
  icon: 'layers'
  color: 'green'