name: 'AWS SAM CLI Deploy'
description: 'Deploy the application to AWS using SAM CLI'
inputs:
  aws-region:
    description: 'AWS Region'
    required: true
  aws-access-key-id:
    description: 'AWS Access Key'
    required: true
  aws-secret-access-key:
    description: 'AWS Secret Key'
    required: true
  aws-acm-arn:
    description: 'AWS ACM ARN'
    required: true
  aws-cloudfront-distribution:
    description: 'AWS Cloudfront Distribution'
    required: true
  to-email:
    description: 'Forward emails to this address'
    required: true
  from-email:
    description: 'Send forwarded emails from this address'
    required: true
  aws-bucket:
    description: 'Name of the bucket to monitor for emails'
    required: true
  aws-account-id:
    description: 'AWS Account ID'
    required: true
runs:
  using: "composite"
  steps:
    - name: Add mask
      shell: sh
      run: |
        echo "::add-mask::${{ inputs.aws-access-key-id }}"
        echo "::add-mask::${{ inputs.aws-secret-access-key }}"
        echo "::add-mask::${{ inputs.aws-acm-arn }}"
        echo "::add-mask::${{ inputs.aws-cloudfront-distribution }}"
        echo "::add-mask::${{ inputs.to-email }}"
        echo "::add-mask::${{ inputs.from-email }}"
    - name: Setup SAM     
      shell: sh
      run: |
        sudo apt-get -y install --no-install-recommends awscli
        curl -L "https://github.com/aws/aws-sam-cli/releases/latest/download/aws-sam-cli-linux-x86_64.zip" -o sam.zip
        unzip sam.zip -d ./sam
        rm sam.zip
        sudo ./sam/install --update
        rm -rf ./sam
    - name: Set up AWS credentials
      shell: sh
      run: |
        aws configure set aws_access_key_id ${{ inputs.aws-access-key-id }}
        aws configure set aws_secret_access_key ${{ inputs.aws-secret-access-key }}
        aws configure set default.region ${{ inputs.aws-region }}
        aws configure set default.output json
    - name: Stage Artifacts 
      shell: sh
      run: |
        mkdir -p ./site/build
        mkdir -p ./rust-lambda/target/contact
        mkdir -p ./rust-lambda/target/email-forward
        unzip ./artifacts/dylanlangston.com-v*.zip -d ./site/build
        unzip ./artifacts/dylanlangston.com-contact-v*.zip -d ./rust-lambda/target/contact
        unzip ./artifacts/dylanlangston.com-email-v*.zip -d ./rust-lambda/target/email-forward
    - name: Deploy Lambda with SAM
      shell: sh
      run: |
        sam deploy --parameter-overrides SslCertificateArn=${{ inputs.aws-acm-arn }} ToEmail=${{ inputs.to-email }} FromEmail=${{ inputs.from-email }} AwsS3BucketName=${{ inputs.aws-bucket }} AwsRegion=${{ inputs.aws-region }} AwsAccountId=${{ inputs.aws-account-id }}
    - name: Deploy Site with CLI
      shell: sh
      run: |
        aws s3 cp ./site/build s3://dylanlangston.com/ --recursive --acl public-read
        aws cloudfront create-invalidation --distribution-id ${{ inputs.aws-cloudfront-distribution }} --paths "/*"
branding:
  icon: 'server'
  color: 'green'