name: 'Docker Image Cache'
description: 'Caching docker image, Loads docker image or build a new one'
inputs:
  tag:
    description: 'Docker tag'
    required: true
  target:
    description: 'Dockerimage Target'
    required: true
runs:
  using: "composite"
  steps:
    - name: Add mask
      shell: sh
      run: |
        echo "::add-mask::${{ inputs.token }}"
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    - name: Build and Push
      uses: docker/build-push-action@v5
      with:
        context: .
        tags: "${{ inputs.tag }}"
        target: "${{ inputs.target }}"
        cache-from: type=gha
        cache-to: type=gha,mode=max
branding:
  icon: 'layers'
  color: 'green'