name: 'Docker Image Cache'
description: 'Caching docker image, Loads docker image or build a new one'
inputs:
  tag:
    description: 'Docker tag'
    required: true
  target:
    description: 'Dockerimage Target'
    required: true
runs:
  using: "composite"
  steps:
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
      with:
        buildkitd-flags: "--allow-insecure-entitlement network.host"
        install: true
    - name: Build and Push
      uses: docker/build-push-action@v6
      with:
        context: .
        allow: network.host
        network: host
        tags: "${{ inputs.tag }}"
        target: "${{ inputs.target }}"
        load: true
        cache-from: type=gha
        cache-to: type=gha,mode=min
    # - name: Prune dangling build cache
    #   shell: sh
    #   run: docker buildx prune -f
branding:
  icon: 'layers'
  color: 'green'
