name: 'Docker Image Cache'
description: 'Caching docker image, Loads docker image or build a new one'
inputs:
  key:
    description: 'Cache Key'
    required: true
  target:
    description: 'Dockerimage Target'
    required: true
  tag:
    description: 'Docker tag'
    required: true
  image:
    description: 'Docker image filename'
    required: true
    default: './cached-docker-image'
runs:
  using: "composite"
  steps:
    - name: Build Docker Image
      shell: sh
      run: docker build --push --rm --network host -t ${{ inputs.tag }} --target ${{ inputs.target }} . --cache-to type=gha --cache-from type=gha
branding:
  icon: 'layers'
  color: 'green'