name: 'Docker Image Cache'
description: 'Caching docker image, Loads docker image or build a new one'
inputs:
  key:
    description: 'Cache Key'
    required: true
  target:
    description: 'Dockerimage Target'
    required: true
  tag:
    description: 'Docker tag'
    required: true
  image:
    description: 'Docker tag'
    required: true
    default: './cached-docker-image'
runs:
  using: "composite"
  steps:
    - name: Cache docker image
      id: cache
      uses: actions/cache@v4
      with:
        path: ${{ inputs.image }}
        key: ${{ inputs.key }}
    - name: Load Docker Image
      if: steps.cache.outputs.cache-hit == 'true'
      shell: sh
      run: docker load -i ${{ inputs.image }}
    - name: Build Docker Image
      if: steps.cache.outputs.cache-hit != 'true'
      shell: sh
      run: docker build -t ${{ inputs.tag }} --target ${{ inputs.target }} --cache-to type=inline .
    - name: Save Docker Image
      if: steps.cache.outputs.cache-hit != 'true'
      shell: sh
      run: docker save -o ${{ inputs.image }} ${{ inputs.tag }}