name: 'Docker Image Cache'
description: 'Caching docker image, Loads docker image or build a new one'
inputs:
  tag:
    description: 'Docker tag'
    required: true
  username:
    description: 'Dockerhub Username'
    required: true
  token:
    description: 'Dockerhub Token'
    required: true
runs:
  using: "composite"
  steps:
    - name: Add mask
      shell: sh
      run: |
        echo "::add-mask::${{ inputs.username }}"
        echo "::add-mask::${{ inputs.token }}"
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: "${{ inputs.username }}"
        password: "${{ inputs.token }}"
    - name: Build and Push
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: "${{ inputs.tag }}"
        cache-from: type=gha
        cache-to: type=gha,mode=max
branding:
  icon: 'layers'
  color: 'green'