name: 'Docker Image Cache'
description: 'Caching docker image, Loads docker image or build a new one'
inputs:
  key:
    description: 'Cache Key'
    required: true
  target:
    description: 'Dockerimage Target'
    required: true
  tag:
    description: 'Docker tag'
    required: true
runs:
  using: "composite"
  steps:
    - name: Cache docker image
      id: cache
      uses: actions/cache@v4
      with:
        path: |
          ./cached-docker-image
        key: ${{ inputs.key }}
    - name: Load docker image or build a new one
      shell: bash
      run: ./DockerCache.sh ./cached-docker-image ${{ inputs.tag }} ${{ inputs.target }}