name: 'Docker Image Cache'
description: 'Caching docker image, Loads docker image or build a new one'
inputs:
  key:
    description: 'Cache Key'
    required: true
  target:
    description: 'Dockerimage Target'
    required: true
  tag:
    description: 'Docker tag'
    required: true
  image:
    description: 'Docker image filename'
    required: true
    default: './cached-docker-image'
runs:
  using: "composite"
  steps:
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Build and Push
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: "dylanlangston.com:build"
        cache-from: type=gha
        cache-to: type=gha,mode=max
branding:
  icon: 'layers'
  color: 'green'