name: 'Docker Image Cache'
description: 'Caching docker image, '
inputs:
  key:
    description: 'Cache Key'
    required: true
  target:
    description: 'Dockerimage Target'
    required: true
  tag:
    description: 'Docker tag'
    required: true
runs:
  using: "composite"
  steps:
    - name: Cache docker image
      id: cache
      uses: actions/cache@v3
      with:
        path: |
          ./cached-docker-image
        key: ${{ inputs.key }}
    - name: Load docker image or build a new one
      shell: bash
      run: |
        [ -f ./cached-docker-image ] && (docker load -i ./cached-docker-image) || (docker build -t ${{ inputs.tag }} --target ${{ inputs.target }} --cache-to type=inline . && docker save -o ./cached-docker-image ${{ inputs.tag }})