name: 'Populate Build Summary'
description: 'Populates the build summary with the appropriate info.'
inputs:
  version:
    description: 'Current Build Version'
    required: false
    default: 'UNKNOWN'
runs:
  using: "node20"
  main: "main.mjs"
  post-if: "always()"
  post: "post.mjs"
branding:
  icon: 'file-text'
  color: 'green'