name: 'Populate Build Summary'
description: 'Populates the build summary with the appropriate info.'
inputs:
  version:
    description: 'Current Build Version'
    required: false
    default: 'UNKNOWN'
    type: string
  mode:
    description: 'A supported mode to generate the build summary.'
    required: true 
    type: string
  runId:
    description: 'Current Workflow Run ID.'
    required: true
    type: string
runs:
  using: "node20"
  main: "main.mjs"
  post: "post.mjs"
branding:
  icon: 'file-text'
  color: 'green'