name: 'Populate Build Summary'
description: 'Populates the build summary with the appropriate info.'
inputs:
  version:
    description: 'Current Build Version'
    required: true
runs:
  using: "node20"
  main: "blank.js"
  post-if: "always()"
  post: "main.mjs"
branding:
  icon: 'file-text'
  color: 'green'