name: 2️⃣ - Build Site

on:
  workflow_call:
    inputs:
      version:
        required: true
        type: string

permissions:
  contents: read

concurrency:
  group: "build"
  cancel-in-progress: true

jobs:
  Build:
    name: "Build 🧰"
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Build Summary
        uses: dylanlangston/dylanlangston.com/.github/actions/PopulateBuildSummary@main
        id: summary
        with:
          version: ${{ inputs.version }}
          mode: 'build'
          runId: ${{ github.run_id }}
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4
      - name: Checkout Submodules
        run: make setup-git-clone
      - name: Cache Docker Image
        uses: dylanlangston/dylanlangston.com/.github/actions/DockerCache@main
        with:
          key: docker-${{ runner.os }}-${{ hashFiles('Dockerfile', '.github/workflows/*.yml', 'Makefile', '**/bun*', '.gitmodules') }}
          target: default
          tag: dylanlangston.com:build
      - name: Build using Docker
        run: make release-docker VERSION=${{ inputs.version }} OPTIMIZE='ReleaseFast'
      - name: Upload Release artifact
        id: upload
        uses: actions/upload-artifact@v4
        with:
          name: dylanlangston.com-v${{ inputs.version }}
          path: '${{ github.workspace }}/site/build'
      - name: Upload GitGub Pages artifact
        id: upload-compressed
        uses: actions/upload-pages-artifact@v3
        with:
          path: '${{ github.workspace }}/site/build'