name: Build and Deploy Pages

on:
  push:
    branches: ["main"]
    
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    outputs:
      datetime: ${{ steps.set_datetime.outputs.datetime }}
    steps:
      - name: Set datetime output variable
        uses: actions/github-script@v7
        id: set_datetime
        with:
          result-encoding: string
          script: |
            const date = new Date(${{ github.event.head_commit.timestamp }});

            const major = 1;
            const minor = parseInt(date.getFullYear()-2000+""+date.getMonth()+""+date.getDate());
            const patch = parseInt(date.getHours()+""+date.getMinutes()+""+date.getSeconds());

            core.exportVariable('datetime', `${major}.${minor}.${patch}`);
            core.notice(`Version: ${major}.${minor}.${patch}`);
      - name: Setup Pages
        uses: actions/configure-pages@v4
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4
      - name: Setup Submodules
        run: make setup-git-clone
      - name: Cache Docker Image
        uses: ./.github/actions/DockerCache
        with:
          key: docker-${{ runner.os }}-${{ hashFiles('Dockerfile', '.github/workflows/*.yml', 'Makefile', '**/bun*', '.gitmodules') }}
          target: default
          tag: dylanlangston.com:build
      - name: Make using docker
        run: make release-docker VERSION=${{ steps.set_datetime.outputs.datetime }} OPTIMIZE='ReleaseFast'
      - name: Upload artifact
        id: upload
        uses: actions/upload-artifact@v4
        with:
          name: dylanlangston.com-v${{ steps.set_datetime.outputs.datetime }}
          path: '${{ github.workspace }}/site/build'
      - name: Upload github pages artifact
        id: upload-compressed
        uses: actions/upload-pages-artifact@v3
        with:
          path: '${{ github.workspace }}/site/build'

  deploy-github-pages:
    runs-on: ubuntu-latest
    timeout-minutes: 1
    needs: [build]
    permissions:
      pages: write      # to deploy to Pages
      id-token: write   # to verify the deployment originates from an appropriate source
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
