name: 🤖 Dependabot Auto-Merge
on: pull_request

permissions:
  contents: write
  pull-requests: write

concurrency:
  group: merge-${{ github.ref }}
  cancel-in-progress: false

jobs:
  Initialize:
    name: "Initialize Workflow ⏳"
    runs-on: ubuntu-latest
    timeout-minutes: 1
    outputs:
      version: ${{ steps.get_version.outputs.version }}
    steps:
      - name: Initialize Summary
        uses: dylanlangston/dylanlangston.com/.github/actions/PopulateBuildSummary@main
        id: summary
        with:
          version: ${{ steps.get_version.outputs.version }}
          mode: 'automerge'
          runId: ${{ github.run_id }}
      - name: Get Version
        uses: dylanlangston/dylanlangston.com/.github/actions/VersionString@main
        id: get_version
        with:
          time: ${{ github.event.pull_request.head.repo.updated_at }}
  Test:
    name: "Step 1️⃣"
    uses: dylanlangston/dylanlangston.com/.github/workflows/Test.yml@main
    needs: [Initialize]
    permissions:
      contents: read
    with:
      version: ${{ needs.Initialize.outputs.version }}
      shouldCache: false
  dependabot:
    name: "Enable Auto-Merge ✅"
    runs-on: ubuntu-latest
    needs: [Test]
    if: github.actor == 'dependabot[bot]'
    steps:
      - name: Enable auto-merge for Dependabot PRs
        run: |
          COMMAND='gh pr merge --auto --merge "$PR_URL"'
          MAX_TRIES=5
          INITIAL_SLEEP=5
          MAX_SLEEP=30
          TRIES=0

          generate_sleep_time() {
              local min_sleep=$1
              local max_sleep=$2
              echo $(( min_sleep + RANDOM % (max_sleep - min_sleep + 1) ))
          }

          while true; do
              $COMMAND
              if [ $? -eq 0 ]; then
                  echo "Pull request merged successfully."
                  break
              else
                  TRIES=$((TRIES+1))
                  if [ $TRIES -eq $MAX_TRIES ]; then
                      echo "Maximum number of tries reached. Giving up."
                      exit 1
                  else
                      echo "Merge failed. Retrying..."
                      sleep_time=$(generate_sleep_time $INITIAL_SLEEP $MAX_SLEEP)
                      echo "Sleeping for $sleep_time seconds before retrying..."
                      sleep $sleep_time
                      INITIAL_SLEEP=$((INITIAL_SLEEP * 2))
                      if [ $INITIAL_SLEEP -gt $MAX_SLEEP ]; then
                          INITIAL_SLEEP=$MAX_SLEEP
                      fi
                  fi
              fi
          done
        env:
          PR_URL: ${{github.event.pull_request.html_url}}
          GH_TOKEN: ${{secrets.PERSONAL_ACCESS_TOKEN}}
