name: 🤖 Dependabot Auto-Merge
on: pull_request

permissions:
  contents: write
  pull-requests: write

concurrency:
  group: merge-${{ github.ref }}
  cancel-in-progress: false

jobs:
  Initialize:
    name: "Initialize Workflow ⏳"
    runs-on: ubuntu-latest
    timeout-minutes: 1
    outputs:
      version: ${{ steps.get_version.outputs.version }}
    steps:
      - name: Initialize Summary
        uses: dylanlangston/dylanlangston.com/.github/actions/PopulateBuildSummary@main
        id: summary
        with:
          version: ${{ steps.get_version.outputs.version }}
          mode: 'automerge'
          runId: ${{ github.run_id }}
      - name: Get Version
        uses: dylanlangston/dylanlangston.com/.github/actions/VersionString@main
        id: get_version
        with:
          time: ${{ github.event.pull_request.head.repo.updated_at }}
  Test:
    name: "Step 1️⃣"
    uses: dylanlangston/dylanlangston.com/.github/workflows/Test.yml@main
    needs: [Initialize]
    permissions:
      contents: read
    with:
      version: ${{ needs.Initialize.outputs.version }}
      shouldCache: false
  dependabot:
    name: "Enable Auto-Merge ✅"
    runs-on: ubuntu-latest
    needs: [Test]
    if: github.actor == 'dependabot[bot]'
    steps:
      - name: Enable auto-merge for Dependabot PRs
        run: |
          for i in $(seq 1 5); do
            if gh pr merge --auto --merge "$PR_URL"; then
              break
            elif [ $? -eq 1 ]; then
              sleep $(shuf -i 5-15 -n 1)
            else
              exit 1
            fi
          done
        env:
          PR_URL: ${{github.event.pull_request.html_url}}
          GH_TOKEN: ${{secrets.PERSONAL_ACCESS_TOKEN}}
