name: ⛘ On Merge

on:
  pull_request:
    branches: 
      - main
    types: [closed]

permissions:
  packages: read
  contents: write
  id-token: write

concurrency:
  group: "onpush"
  cancel-in-progress: true

jobs:
  Initialize:
    if: ${{ github.event.pull_request.merged }}
    name: "Initialize Workflow ⏳"
    runs-on: ubuntu-latest
    timeout-minutes: 1
    outputs:
      version: ${{ steps.get_version.outputs.version }}
    steps:
      - name: Initialize Summary
        uses: dylanlangston/dylanlangston.com/.github/actions/PopulateBuildSummary@main
        id: summary
        with:
          version: ${{ steps.get_version.outputs.version }}
          mode: 'onpush'
          runId: ${{ github.run_id }}
      - name: Get Version
        uses: dylanlangston/dylanlangston.com/.github/actions/VersionString@main
        id: get_version
        with:
          time: ${{ github.event.head_commit.timestamp }}
  Build:
    if: ${{ github.event.pull_request.merged }}
    name: "Step 2️⃣"
    uses: dylanlangston/dylanlangston.com/.github/workflows/Build.yml@main
    needs: [Initialize]
    permissions:
      contents: read
    with:
      version: ${{ needs.Initialize.outputs.version }}
  Deploy:
    if: ${{ github.event.pull_request.merged }}
    name: "Step 3️⃣"
    uses: dylanlangston/dylanlangston.com/.github/workflows/Deploy.yml@main
    needs: [Initialize, Build]
    permissions:
      contents: read
      pages: write
      id-token: write
    with:
      version: ${{ needs.Initialize.outputs.version }}
  Release:
    if: ${{ github.event.pull_request.merged }}
    name: "Step 4️⃣"
    uses: dylanlangston/dylanlangston.com/.github/workflows/Release.yml@main
    needs: [Initialize, Deploy]
    permissions:
      packages: read
      contents: write
    with:
      version: ${{ needs.Initialize.outputs.version }}
      commit-message: ${{ github.event.head_commit.message }}
      runId: ${{ github.run_id }}