name: Release Site To Production

on:
  workflow_run:
    workflows: ["Build and Deploy Pages"]
    types: [completed]

jobs:
  publish-release:
    runs-on: ubuntu-latest
    timeout-minutes: 1
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    permissions:
      packages: read
      contents: read
    environment:
      name: production
    steps:
      - name: Set current datetime output variable
        id: set_datetime
        run: echo "datetime=1.$(echo $(date --date="${{ github.event.workflow_run.head_commit.timestamp }}" +"%y%m%d") | sed 's/^0*//').$(echo $(date --date="${{ github.event.workflow_run.head_commit.timestamp }}" +"%H%M%S") | sed 's/^0*//')" >> "$GITHUB_OUTPUT"
      - name: 'Download artifact'
        uses: actions/github-script@v6
        with:
          script: |
            let allArtifacts = await github.rest.actions.listWorkflowRunArtifacts({
               owner: context.repo.owner,
               repo: context.repo.repo,
               run_id: context.payload.workflow_run.id,
            });
            let matchArtifact = allArtifacts.data.artifacts.filter((artifact) => {
              return artifact.name == "release-artifact"
            })[0];
            let download = await github.rest.actions.downloadArtifact({
               owner: context.repo.owner,
               repo: context.repo.repo,
               artifact_id: matchArtifact.id,
               archive_format: 'zip',
            });
            let fs = require('fs');
            fs.writeFileSync(`${process.env.GITHUB_WORKSPACE}/dylanlangstoncom-v${{ steps.set_datetime.outputs.datetime }}.zip`, Buffer.from(download.data));
      - name: Create Release
        id: create_release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "dylanlangstoncom-v${{ steps.set_datetime.outputs.datetime }}.zip"
          artifactContentType: application/zip
          body: |
            **DylanLangston.com - _Prerelease v${{ steps.set_datetime.outputs.datetime }}_**
            ${{ github.event.workflow_run.head_commit.message }}
          prerelease: true
          draft: false
          commit: ${{ github.head_ref }}
          tag: v${{ steps.set_datetime.outputs.datetime }}
          token: ${{ secrets.GITHUB_TOKEN }}
